# Ex1 - Filtering and Sorting Data

This time we are going to pull data directly from the internet.
Special thanks to: https://github.com/justmarkham for sharing the dataset and materials.

### Step 1. Import the necessary libraries

In [38]:
import pandas as pd
import re

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv).

### Step 3. Assign it to a variable called chipo.

In [39]:
chipo = pd.read_csv('https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv', sep='\t')
chipo = chipo.drop_duplicates(subset=['item_name', 'choice_description'])

### Step 4. How many products cost more than $10.00?

In [40]:
chipo.item_price = chipo.item_price.apply(lambda pr: re.search(r'\d+\.?\d*', pr).group()).astype('float64')
chipo['product_price'] = chipo.item_price / chipo.quantity
flt = chipo.loc[chipo.product_price > 10]
flt.shape[0]

707

### Step 5. What is the price of each item? 
###### print a data frame with only three columns item_name choice_description and product_price

In [42]:
flt[['item_name', 'choice_description', 'product_price']]

,item_name,choice_description,product_price
5,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",10.98
7,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",11.75
13,Chicken Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25
23,Chicken Burrito,"[[Tomatillo-Green Chili Salsa (Medium), Tomati...",10.98
39,Barbacoa Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",11.75
...,...,...,...
4593,Carnitas Bowl,"[Roasted Chili Corn Salsa, [Rice, Sour Cream, ...",11.75
4594,Barbacoa Bowl,"[Roasted Chili Corn Salsa, [Pinto Beans, Sour ...",11.75
4607,Steak Burrito,"[Tomatillo Green Chili Salsa, [Rice, Cheese, S...",11.75
4610,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",11.75
4611,Veggie Burrito,"[Tomatillo Green Chili Salsa, [Rice, Fajita Ve...",11.25

### Step 6. Sort by the name of the item

In [43]:
chipo.sort_values('item_name')

,order_id,quantity,item_name,choice_description,item_price,product_price
341,148,1,6 Pack Soft Drink,[Diet Coke],6.49,6.49
298,129,1,6 Pack Soft Drink,[Sprite],6.49,6.49
357,154,1,6 Pack Soft Drink,[Coke],6.49,6.49
721,298,1,6 Pack Soft Drink,[Nestea],6.49,6.49
3141,1253,1,6 Pack Soft Drink,[Lemonade],6.49,6.49
...,...,...,...,...,...,...
2384,948,1,Veggie Soft Tacos,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",8.75,8.75
738,304,1,Veggie Soft Tacos,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",11.25,11.25
3889,1559,2,Veggie Soft Tacos,"[Fresh Tomato Salsa (Mild), [Black Beans, Rice...",16.98,8.49
1395,567,1,Veggie Soft Tacos,"[Fresh Tomato Salsa (Mild), [Pinto Beans, Rice...",8.49,8.49
781,322,1,Veggie Soft Tacos,"[Fresh Tomato Salsa, [Black Beans, Cheese, Sou...",8.75,8.75

### Step 7. What was the quantity of the most expensive item ordered?

In [46]:
chipo.iloc[chipo.item_price.idxmax()].quantity

np.int64(1)

### Step 8. How many times was a Veggie Salad Bowl ordered?

In [52]:
chipo.loc[chipo.item_name == 'Veggie Salad Bowl'].quantity.sum()

np.int64(16)

### Step 9. How many times did someone order more than one Canned Soda?

In [51]:
chipo.loc[(chipo.item_name == 'Canned Soda') & (chipo.quantity > 1)].shape[0]

3