# US - Baby Names

### Introduction:

We are going to use a subset of [US Baby Names](https://www.kaggle.com/kaggle/us-baby-names) from Kaggle.  
In the file it will be names from 2004 until 2014


### Step 1. Import the necessary libraries

In [1]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/06_Stats/US_Baby_Names/US_Baby_Names_right.csv).

### Step 3. Assign it to a variable called baby_names.

In [4]:
baby_names = pd.read_csv('https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/06_Stats/US_Baby_Names/US_Baby_Names_right.csv')

### Step 4. See the first 10 entries

In [5]:
baby_names.head(10)

   Unnamed: 0     Id      Name  Year Gender State  Count
0       11349  11350      Emma  2004      F    AK     62
1       11350  11351   Madison  2004      F    AK     48
2       11351  11352    Hannah  2004      F    AK     46
3       11352  11353     Grace  2004      F    AK     44
4       11353  11354     Emily  2004      F    AK     41
5       11354  11355   Abigail  2004      F    AK     37
6       11355  11356    Olivia  2004      F    AK     33
7       11356  11357  Isabella  2004      F    AK     30
8       11357  11358    Alyssa  2004      F    AK     29
9       11358  11359    Sophia  2004      F    AK     28

### Step 5. Delete the column 'Unnamed: 0' and 'Id'

In [6]:
baby_names = baby_names.drop(columns=['Unnamed: 0', 'Id'])

### Step 6. What year has the highest number of baby names in the dataset?

In [40]:
baby_names.groupby('Year').Count.sum().sort_values(ascending=False).head(1)

Year
2007    3412417
Name: Count, dtype: int64

### Step 7. Is there more male or female names in the dataset?

In [47]:
baby_names.Gender.value_counts()

Gender
F    558846
M    457549
Name: count, dtype: int64

### Step 8. Group the dataset by name and assign to names

In [51]:
names = baby_names.groupby('Name', as_index=False).Count.sum().sort_values('Count', ascending=False)
names.head()

           Name   Count
7198      Jacob  242874
5378       Emma  214852
12111   Michael  214405
5579      Ethan  209277
6973   Isabella  204798

### Step 9. How many different names exist in the dataset?

In [18]:
baby_names.Name.nunique()

17632

### Step 10. What is the name with most occurrences?

In [52]:
names.head(1)

       Name   Count
7198  Jacob  242874

### Step 11. How many different names have the least occurrences?

In [55]:
names.loc[names.Count == names.Count.min()].shape[0]

2578

### Step 12. What is the median name occurrence?

In [56]:
names.loc[names.Count == names.Count.median()]

           Name  Count
8800   Kaedence     49
10649  Leylanie     49
12493    Nabeel     49
3143     Caleah     49
12666    Nassir     49
...         ...    ...
10204   Kynsley     49
5801        Fay     49
11814  Maurilio     49
11535   Mariann     49
2382      Baily     49

[66 rows x 2 columns]

### Step 13. What is the standard deviation of names?

In [57]:
names.Count.std()

np.float64(11006.06946789057)

### Step 14. Get a summary with the mean, min, max, std and quartiles.

In [58]:
names.describe()

               Count
count   17632.000000
mean     2008.932169
std     11006.069468
min         5.000000
25%        11.000000
50%        49.000000
75%       337.000000
max    242874.000000