# Wind Statistics

### Introduction:

The data have been modified to contain some missing values, identified by NaN.  
Using pandas should make this exercise
easier, in particular for the bonus question.

You should be able to perform all of these operations without using
a for loop or other looping construct.


1. The data in 'wind.data' has the following format:

In [31]:
"""
Yr Mo Dy   RPT   VAL   ROS   KIL   SHA   BIR   DUB   CLA   MUL   CLO   BEL   MAL
61  1  1 15.04 14.96 13.17  9.29   NaN  9.87 13.67 10.25 10.83 12.58 18.50 15.04
61  1  2 14.71   NaN 10.83  6.50 12.62  7.67 11.50 10.04  9.79  9.67 17.54 13.83
61  1  3 18.50 16.88 12.33 10.13 11.17  6.17 11.25   NaN  8.50  7.67 12.75 12.71
"""

'\nYr Mo Dy   RPT   VAL   ROS   KIL   SHA   BIR   DUB   CLA   MUL   CLO   BEL   MAL\n61  1  1 15.04 14.96 13.17  9.29   NaN  9.87 13.67 10.25 10.83 12.58 18.50 15.04\n61  1  2 14.71   NaN 10.83  6.50 12.62  7.67 11.50 10.04  9.79  9.67 17.54 13.83\n61  1  3 18.50 16.88 12.33 10.13 11.17  6.17 11.25   NaN  8.50  7.67 12.75 12.71\n'

   The first three columns are year, month and day.  The
   remaining 12 columns are average windspeeds in knots at 12
   locations in Ireland on that day.   

   More information about the dataset go [here](wind.desc).

### Step 1. Import the necessary libraries

In [32]:
import pandas as pd 
import datetime

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/06_Stats/Wind_Stats/wind.data)

### Step 3. Assign it to a variable called data and replace the first 3 columns by a proper datetime index.

In [33]:
data = pd.read_csv('https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/06_Stats/Wind_Stats/wind.data', sep=r'\s+')

data['date'] = '20' + data.Yr.astype(str) + '-' + data.Mo.astype(str).str.rjust(2, '0') + '-' + data.Dy.astype(str).str.rjust(2, '0')
data.date = pd.to_datetime(data.date)
data.head()

,Yr,Mo,Dy,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL,date
0,61,1,1,15.04,14.96,13.17,9.29,NaN,9.87,13.67,10.25,10.83,12.58,18.50,15.04,2061-01-01
1,61,1,2,14.71,NaN,10.83,6.50,12.62,7.67,11.50,10.04,9.79,9.67,17.54,13.83,2061-01-02
2,61,1,3,18.50,16.88,12.33,10.13,11.17,6.17,11.25,NaN,8.50,7.67,12.75,12.71,2061-01-03
3,61,1,4,10.58,6.63,11.75,4.58,4.54,2.88,8.63,1.79,5.83,5.88,5.46,10.88,2061-01-04
4,61,1,5,13.33,13.25,11.42,6.17,10.71,8.21,11.92,6.54,10.92,10.34,12.92,11.83,2061-01-05

### Step 4. Year 2061? Do we really have data from this year? Create a function to fix it and apply it.

In [34]:
def date_fixer(date: datetime.date, threshold: int) -> pd.Timestamp:
    new_year = date.year - threshold
    try: 
        return pd.Timestamp(year=new_year, month=date.month, day=date.day)
    except ValueError:
        return None

max_yr = data.date.max()
threshold = max_yr.year - 2026

data.date = data.date.apply(date_fixer, (threshold,))
data.head()

,Yr,Mo,Dy,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL,date
0,61,1,1,15.04,14.96,13.17,9.29,NaN,9.87,13.67,10.25,10.83,12.58,18.50,15.04,2009-01-01
1,61,1,2,14.71,NaN,10.83,6.50,12.62,7.67,11.50,10.04,9.79,9.67,17.54,13.83,2009-01-02
2,61,1,3,18.50,16.88,12.33,10.13,11.17,6.17,11.25,NaN,8.50,7.67,12.75,12.71,2009-01-03
3,61,1,4,10.58,6.63,11.75,4.58,4.54,2.88,8.63,1.79,5.83,5.88,5.46,10.88,2009-01-04
4,61,1,5,13.33,13.25,11.42,6.17,10.71,8.21,11.92,6.54,10.92,10.34,12.92,11.83,2009-01-05

### Step 5. Set the right dates as the index. Pay attention at the data type, it should be datetime64[ns].

In [35]:
data = data.set_index('date')
data = data.drop(columns=['Yr', 'Mo', 'Dy'])
data.head()

,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
date,,,,,,,,,,,,
2009-01-01,15.04,14.96,13.17,9.29,NaN,9.87,13.67,10.25,10.83,12.58,18.50,15.04
2009-01-02,14.71,NaN,10.83,6.50,12.62,7.67,11.50,10.04,9.79,9.67,17.54,13.83
2009-01-03,18.50,16.88,12.33,10.13,11.17,6.17,11.25,NaN,8.50,7.67,12.75,12.71
2009-01-04,10.58,6.63,11.75,4.58,4.54,2.88,8.63,1.79,5.83,5.88,5.46,10.88
2009-01-05,13.33,13.25,11.42,6.17,10.71,8.21,11.92,6.54,10.92,10.34,12.92,11.83

### Step 6. Compute how many values are missing for each location over the entire record.  
#### They should be ignored in all calculations below.

In [36]:
data.isna().sum()

RPT    6
VAL    3
ROS    2
KIL    5
SHA    2
BIR    0
DUB    3
CLA    2
MUL    3
CLO    1
BEL    0
MAL    4
dtype: int64

### Step 7. Compute how many non-missing values there are in total.

In [37]:
data.isna().sum().sum()

np.int64(31)

### Step 8. Calculate the mean windspeeds of the windspeeds over all the locations and all the times.
#### A single number for the entire dataset.

In [38]:
data.mean().mean()

np.float64(10.227982360836938)

### Step 9. Create a DataFrame called loc_stats and calculate the min, max and mean windspeeds and standard deviations of the windspeeds at each location over all the days 

#### A different set of numbers for each location.

In [39]:
loc_stats = data.describe()
loc_stats = loc_stats.reindex(index=['min', 'max', 'mean', 'std'])
loc_stats

,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
min,0.670000,0.210000,1.500000,0.000000,0.130000,0.000000,0.000000,0.000000,0.000000,0.040000,0.130000,0.670000
max,35.800000,33.370000,33.840000,28.460000,37.540000,26.160000,30.370000,31.080000,25.880000,28.210000,42.380000,42.540000
mean,12.362987,10.644314,11.660526,6.306468,10.455834,7.092254,9.797343,8.495053,8.493590,8.707332,13.121007,15.599079
std,5.618413,5.267356,5.008450,3.605811,4.936125,3.968683,4.977555,4.499449,4.166872,4.503954,5.835037,6.699794

### Step 10. Create a DataFrame called day_stats and calculate the min, max and mean windspeed and standard deviations of the windspeeds across all the locations at each day.

#### A different set of numbers for each day.

In [91]:
day_stats = data.agg(['min', 'max', 'mean', 'std'], axis=1)
day_stats

             min    max       mean       std
date
2009-01-01  9.29  18.50  13.018182  2.808875
2009-01-02  6.50  17.54  11.336364  3.188994
2009-01-03  6.17  18.50  11.641818  3.681912
2009-01-04  1.79  11.75   6.619167  3.198126
2009-01-05  6.17  13.33  10.630000  2.445356
...          ...    ...        ...       ...
2026-12-27  8.08  40.08  16.708333  7.868076
2026-12-28  5.00  41.46  15.150000  9.687857
2026-12-29  8.71  29.58  14.890000  5.756836
2026-12-30  9.13  28.79  15.367500  5.540437
2026-12-31  9.59  27.29  15.402500  5.702483

[6574 rows x 4 columns]

### Step 11. Find the average windspeed in January for each location.  
#### Treat January 1961 and January 1962 both as January.

In [65]:
data.loc[data.index.month == 1].mean()

RPT    14.847325
VAL    12.914560
ROS    13.299624
KIL     7.199498
SHA    11.667734
BIR     8.054839
DUB    11.819355
CLA     9.512047
MUL     9.543208
CLO    10.053566
BEL    14.550520
MAL    18.028763
dtype: float64

### Step 12. Downsample the record to a yearly frequency for each location.

In [92]:
data.resample('YE').mean()

,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
date,,,,,,,,,,,,
2009-12-31,12.299583,10.351796,11.362369,6.958227,10.881763,7.729726,9.733923,8.858788,8.647652,9.835577,13.502795,13.680773
2010-12-31,12.246923,10.110438,11.732712,6.960440,10.657918,7.393068,11.020712,8.793753,8.316822,9.676247,12.930685,14.323956
2011-12-31,12.813452,10.836986,12.541151,7.330055,11.724110,8.434712,11.075699,10.336548,8.903589,10.224438,13.638877,14.999014
2012-12-31,12.363661,10.920164,12.104372,6.787787,11.454481,7.570874,10.259153,9.467350,7.789016,10.207951,13.740546,14.910301
2013-12-31,12.451370,11.075534,11.848767,6.858466,11.024795,7.478110,10.618712,8.879918,7.907425,9.918082,12.964247,15.591644
2014-12-31,13.461973,11.557205,12.020630,7.345726,11.805041,7.793671,10.579808,8.835096,8.514438,9.768959,14.265836,16.307260
2015-12-31,12.737151,10.990986,11.739397,7.143425,11.630740,7.368164,10.652027,9.325616,8.645014,9.547425,14.774548,17.135945
2016-12-31,11.835628,10.468197,11.409754,6.477678,10.760765,6.067322,8.859180,8.255519,7.224945,7.832978,12.808634,15.017486
2017-12-31,11.166356,9.723699,10.902000,5.767973,9.873918,6.189973,8.564493,7.711397,7.924521,7.754384,12.621233,15.762904
2018-12-31,12.600329,10.726932,11.730247,6.217178,10.567370,7.609452,9.609890,8.334630,9.297616,8.289808,13.183644,16.456027
2019-12-31,11.273123,9.095178,11.088329,5.241507,9.440329,6.097151,8.385890,6.757315,7.915370,7.229753,12.208932,15.025233
2020-12-31,12.463962,10.561311,12.058333,5.929699,9.430410,6.358825,9.704508,7.680792,8.357295,7.515273,12.727377,15.028716
2021-12-31,11.828466,10.680493,10.680493,5.547863,9.640877,6.548740,8.482110,7.614274,8.245534,7.812411,12.169699,15.441096
2022-12-31,13.643096,11.811781,12.336356,6.427041,11.110986,6.809781,10.084603,9.896986,9.331753,8.736356,13.252959,16.947671
2023-12-31,12.008575,10.293836,11.564712,5.269096,9.190082,5.668521,8.562603,7.843836,8.797945,7.382822,12.631671,15.307863
2024-12-31,11.737842,10.203115,10.761230,5.109426,8.846339,6.311038,9.149126,7.146202,8.883716,7.883087,12.332377,15.471448
2025-12-31,13.099616,11.144493,12.627836,6.073945,10.003836,8.586438,11.523205,8.378384,9.098192,8.821616,13.459068,16.590849
2026-12-31,12.504356,11.044274,11.380000,6.082356,10.167233,7.650658,9.489342,8.800466,9.089753,8.301699,12.967397,16.771370

### Step 13. Downsample the record to a monthly frequency for each location.

In [93]:
data.resample('ME').mean()

,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
date,,,,,,,,,,,,
2009-01-31,14.841333,11.988333,13.431613,7.736774,11.072759,8.588065,11.184839,9.245333,9.085806,10.107419,13.880968,14.703226
2009-02-28,16.269286,14.975357,14.441481,9.230741,13.852143,10.937500,11.890714,11.846071,11.821429,12.714286,18.583214,15.411786
2009-03-31,10.890000,11.296452,10.752903,7.284000,10.509355,8.866774,9.644194,9.829677,10.294138,11.251935,16.410968,15.720000
2009-04-30,10.722667,9.427667,9.998000,5.830667,8.435000,6.495000,6.925333,7.094667,7.342333,7.237000,11.147333,10.278333
2009-05-31,9.860968,8.850000,10.818065,5.905333,9.490323,6.574839,7.604000,8.177097,8.039355,8.499355,11.900323,12.011613
...,...,...,...,...,...,...,...,...,...,...,...,...
2026-08-31,9.645161,8.259355,9.032258,4.502903,7.368065,5.935161,5.650323,5.417742,7.241290,5.536774,10.466774,12.054194
2026-09-30,10.913667,10.895000,10.635000,5.725000,10.372000,9.278333,10.790333,9.583000,10.069333,8.939000,15.680333,19.391333
2026-10-31,9.897742,8.670968,9.295806,4.721290,8.525161,6.774194,8.115484,7.337742,8.297742,8.243871,13.776774,17.150000
2026-11-30,16.151667,14.802667,13.508000,7.317333,11.475000,8.743000,11.492333,9.657333,10.701333,10.676000,17.404667,20.723000
2026-12-31,16.175484,13.748065,15.635161,7.094839,11.398710,9.241613,12.077419,10.194839,10.616774,11.028710,13.859677,21.371613

### Step 14. Downsample the record to a weekly frequency for each location.

In [95]:
data.resample('W').mean()

,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
date,,,,,,,,,,,,
2009-01-04,14.707500,12.823333,12.020000,7.625000,9.443333,6.647500,11.262500,7.360000,8.737500,8.950000,13.562500,13.115000
2009-01-11,12.504286,11.032857,10.917143,5.654286,9.540000,6.987143,10.435714,7.731429,8.137143,9.001429,13.421429,14.195714
2009-01-18,14.964286,9.801429,14.225714,7.131429,7.995000,6.501429,9.464286,7.528571,7.077143,8.810000,10.471429,10.875714
2009-01-25,13.375714,9.620000,13.448571,6.155714,10.494286,8.858571,9.661429,9.394286,7.381429,8.825714,11.845714,14.327143
2009-02-01,19.125000,17.588571,15.314286,11.804286,16.664286,12.911429,14.988571,12.332857,13.577143,13.795714,19.294286,19.364286
...,...,...,...,...,...,...,...,...,...,...,...,...
2026-12-06,19.077143,16.060000,17.427143,8.464286,14.304286,12.577143,15.095714,11.460000,13.060000,13.338571,15.758571,22.164286
2026-12-13,20.771429,19.804286,16.904286,10.062857,15.118571,12.101429,13.227143,12.317143,13.352857,13.911429,17.725714,20.982857
2026-12-20,12.674286,9.562857,12.238571,3.797143,7.177143,3.928571,6.400000,4.948571,5.115714,5.262857,8.280000,14.224286
2026-12-27,11.868571,9.362857,13.855714,4.962857,8.434286,7.342857,9.715714,9.167143,8.512857,8.582857,10.685714,21.501429
2027-01-03,16.510000,11.800000,19.115000,8.107500,10.665000,9.950000,17.707500,13.302500,13.447500,14.492500,16.855000,30.477500

### Step 15. Calculate the min, max and mean windspeeds and standard deviations of the windspeeds across all locations for each week (assume that the first week starts on January 2 1961) for the first 52 weeks.

In [108]:
data.resample('W').agg(['min','max','mean','std']).iloc[:52]

              RPT                                 VAL                    \
              min    max       mean        std    min    max       mean
date
2009-01-04  10.58  18.50  14.707500   3.241907   6.63  16.88  12.823333
2009-01-11  10.58  13.50  12.504286   1.225709   8.12  14.29  11.032857
2009-01-18   9.04  19.83  14.964286   4.574403   3.54  14.37   9.801429
2009-01-25   4.92  25.04  13.375714   6.418735   3.42  14.83   9.620000
2009-02-01  12.21  24.37  19.125000   5.207002  11.42  23.91  17.588571
2009-02-08  10.58  24.54  19.172857   5.233500   9.46  24.21  16.952857
2009-02-15   6.04  22.50  16.617143   5.209193  11.54  19.70  14.541429
2009-02-22   7.79  16.79  13.058571   3.209042   8.63  20.17  13.592857
2009-03-01   8.71  25.80  16.002857   6.321805   7.08  21.50  14.530000
2009-03-08   4.88  13.33   9.571429   3.259378   8.08  17.00  11.188571
2009-03-15  10.63  14.79  11.971667   1.487998  10.17  16.96  13.758571
2009-03-22   4.92  16.88  11.222857   4.563685   4.42  15.25  11.107143
2009-03-29   5.88  18.25   9.990000   4.819841   2.58  16.29   9.102857
2009-04-05   7.62  18.12  12.862857   4.497150   4.25  14.62   9.781429
2009-04-12   4.50  13.37   9.042857   3.088234   4.83  12.25   9.254286
2009-04-19   4.00  16.71   9.631429   5.205367   3.71  13.96   8.424286
2009-04-26   8.17  21.09  13.811429   4.361672   5.66  15.41  11.062857
2009-05-03   4.08  19.04  10.980000   5.291058   6.50  14.83  10.537143
2009-05-10   4.79  23.00  12.182857   6.496860   3.96  19.79  11.201429
2009-05-17   3.54  15.04   9.350000   3.532766   3.92  15.12   8.767143
2009-05-24   4.88   6.83   5.667143   0.771097   3.58   5.96   4.458333
2009-05-31   7.00  12.04   9.911429   1.940261   4.75  12.50   8.477143
2009-06-07   7.50  15.92  10.720000   2.902683   6.34  11.54   8.591429
2009-06-14   6.13  14.42   9.757143   2.743749   4.12  12.42   8.152857
2009-06-21   4.00  14.33  10.250000   3.586080   3.25  14.54   8.924286
2009-06-28   5.71  13.13   8.548571   2.404935   4.21  11.42   7.300000
2009-07-05   7.21  17.50  12.646667   3.526367   4.96  14.37   9.314286
2009-07-12   7.29  19.46  10.977143   4.083061   3.75  16.88   8.631429
2009-07-19   4.25  22.50  13.055714   8.192775   3.08  19.29  10.250000
2009-07-26   3.04  15.92   7.142857   4.880180   2.92  13.79   6.060000
2009-08-02   6.13  16.08   9.544286   3.263116   4.83  10.41   7.225714
2009-08-09   2.88  16.08  11.268571   4.432134   4.42  15.79   9.780000
2009-08-16   6.63  16.42  12.531667   3.512705   6.71  10.88   8.311429
2009-08-23   9.62  18.91  15.067143   3.413911   8.17  14.58  11.308571
2009-08-30   3.63  14.46  11.012857   4.001020   4.67  22.00  12.948571
2009-09-06   4.83  17.62   9.481429   4.656531   1.13  12.54   6.374286
2009-09-13   5.00  20.75  12.005714   6.078547   3.92  18.66  11.007143
2009-09-20   5.33  28.75  14.017143   8.659795   2.92  22.08  10.774286
2009-09-27   6.92  18.46  10.615714   3.772222   6.04  13.62   9.672857
2009-10-04   3.13  23.21  13.382857   7.341800   4.00  13.62   8.708333
2009-10-11   9.75  17.12  14.397143   2.627767   3.63  16.96  11.471429
2009-10-18   3.71  28.62  15.213333  10.684450   6.13  19.46  11.781429
2009-10-25  10.46  26.42  18.900000   5.965749   3.75  21.25  13.827143
2009-11-01   4.33  18.41  11.682857   5.141529   2.75  13.13   8.857143
2009-11-08   5.46  15.79  10.000000   3.868074   3.96  13.46   7.844286
2009-11-15   7.71  16.08  11.714286   3.492615   5.50  13.00   8.947143
2009-11-22   6.46  14.29  10.417143   2.997809   3.29   9.33   5.581429
2009-11-29   5.75  15.67   9.287143   3.402439   4.67  15.67   9.904286
2009-12-06   8.58  23.75  15.452857   6.113359   5.96  18.71  11.835714
2009-12-13  10.83  23.71  17.452857   4.173191  10.96  21.37  14.780000
2009-12-20   9.29  18.05  12.551429   2.710704   8.63  17.62  11.912857
2009-12-27   9.25  24.41  17.665714   5.150873   5.21  16.13  11.862857

                        ROS         ...        CLO              BEL         \
                 std    min    max  ...       mean       std    min    max
date                                ...
2009-01-04  5.448819  10.83  13.17  ...   8.950000  2.872780   5.46  18.50
2009-01-11  2.123525   7.62  19.50  ...   9.001429  1.108609   8.12  20.71
2009-01-18  3.863235   7.08  20.79  ...   8.810000  5.506115   5.25  15.92
2009-01-25  3.815993   7.29  25.84  ...   8.825714  4.807289   6.50  23.09
2009-02-01  4.397656   9.04  22.29  ...  13.795714  5.600863   9.17  27.71
2009-02-08  5.437256  10.00  21.34  ...  11.900000  3.801158   9.71  26.38
2009-02-15  3.109279   6.13  19.67  ...  14.005714  2.394889  14.09  28.62
2009-02-22  3.652774   6.08  14.75  ...  12.130000  2.444136  12.12  29.63
2009-03-01  4.522433  11.17  22.42  ...  13.780000  4.249851   9.59  23.21
2009-03-08  3.603204   7.54  13.67  ...   9.930000  3.139591  10.21  23.45
2009-03-15  2.411952   9.04  16.38  ...  12.297143  2.230835  12.29  22.71
2009-03-22  3.688386   5.25  15.63  ...  11.435714  3.148136   8.25  22.79
2009-03-29  4.888741   4.79  14.96  ...  11.280000  2.975567   7.21  21.34
2009-04-05  3.982919   5.09  18.29  ...   8.142857  2.671764  10.71  17.16
2009-04-12  2.670349   8.25  13.75  ...   6.935714  2.641722   7.62  16.17
2009-04-19  3.667683   3.33  15.79  ...   7.355714  3.784701   5.75  19.21
2009-04-26  3.843378   6.92  17.00  ...   9.182857  2.248205   6.75  18.05
2009-05-03  3.146155   2.54  15.37  ...   6.834286  3.174371   5.13  18.63
2009-05-10  5.719226   4.63  21.21  ...  11.430000  5.932981   4.79  28.08
2009-05-17  3.762458   5.33  15.63  ...   7.025714  2.547998   6.63  12.00
2009-05-24  0.960862   3.58  15.96  ...   6.261429  2.025096   6.13  10.83
2009-05-31  2.763263   6.42  20.96  ...   8.630000  2.731922   8.71  14.33
2009-06-07  1.837357   6.13  12.04  ...   9.382857  1.456614  10.67  17.00
2009-06-14  2.623139   6.04  13.46  ...   7.348571  2.678124   5.37  20.21
2009-06-21  3.584154   5.13  15.50  ...  10.738571  2.250796  11.00  25.25
2009-06-28  2.611564   6.38   9.92  ...  11.802857  1.709763  10.83  19.92
2009-07-05  3.160405   7.62  14.92  ...  11.275714  3.190449   6.96  21.87
2009-07-12  4.318254   7.41  12.29  ...   8.304286  2.532837   5.04  17.21
2009-07-19  6.092919   5.29  14.29  ...  10.018571  2.826608   6.17  20.25
2009-07-26  3.697675   4.08  15.67  ...   7.994286  5.195328   4.21  22.17
2009-08-02  2.221665   5.54  10.29  ...   7.135714  1.466445   6.17  11.17
2009-08-09  3.693201   6.34  15.59  ...   9.398571  2.481414   7.92  18.54
2009-08-16  1.513720   6.00  10.54  ...   9.105000  3.228441   5.88  15.37
2009-08-23  2.668311   9.50  14.62  ...  12.154286  3.367149  10.04  21.92
2009-08-30  5.754122   4.88  17.83  ...  12.877143  4.015938   5.75  24.71
2009-09-06  4.059384   2.42  11.58  ...   7.125714  3.204486   4.79  17.16
2009-09-13  4.786717   3.63  16.66  ...   9.304286  3.282341   5.66  23.91
2009-09-20  7.068158   5.33  26.50  ...  12.005714  7.139393   4.54  23.91
2009-09-27  3.366708   6.46  15.87  ...   9.210000  3.044547  10.46  20.96
2009-10-04  4.049817   4.96  17.58  ...   9.238571  5.618904   4.92  21.37
2009-10-11  4.048574   8.71  20.96  ...  10.377143  3.646952   4.79  20.46
2009-10-18  5.317952   4.21  22.63  ...  13.067143  8.469730  12.46  24.71
2009-10-25  6.219005  10.37  23.09  ...  15.734286  3.739166  10.88  27.29
2009-11-01  4.212239   4.79  17.41  ...  10.101429  3.012991   8.50  20.17
2009-11-08  3.795984   4.83  12.58  ...  10.024286  3.547256   7.67  19.79
2009-11-15  2.835482   3.83  32.71  ...   6.827143  3.958492   3.83  11.00
2009-11-22  2.135200   6.46  14.46  ...   5.488571  2.818400   0.71   9.59
2009-11-29  3.465708   4.42  13.00  ...  10.185714  3.719838   5.50  20.46
2009-12-06  4.830948   8.00  19.92  ...   9.337143  4.317483   7.79  21.79
2009-12-13  3.580861   9.71  20.54  ...  12.988571  4.000831  11.08  22.83
2009-12-20  3.443945   8.08  16.66  ...   6.844286  3.245555   5.29  20.62
2009-12-27  3.841483   8.83  22.13  ...   8.738571  4.898243   3.75  17.67

                                   MAL
                 mean       std    min    max       mean       std
date
2009-01-04  13.562500  5.958469  10.88  15.04  13.115000  1.767871
2009-01-11  13.421429  4.389109  11.83  16.92  14.195714  2.095136
2009-01-18  10.471429  4.321795   5.17  17.96  10.875714  5.086953
2009-01-25  11.845714  6.057378   6.79  25.25  14.327143  6.958874
2009-02-01  19.294286  6.699054   8.00  27.63  19.364286  6.824443
2009-02-08  17.571429  6.028215   7.17  21.84  14.482857  5.520524
2009-02-15  21.040000  5.075155  10.96  21.09  16.734286  4.008927
2009-02-22  18.685714  5.749165   6.67  22.58  15.155714  5.458504
2009-03-01  18.671429  4.706724   9.21  23.87  16.486667  5.449237
2009-03-08  15.677143  4.628393   5.54  16.38  11.808571  4.079050
2009-03-15  19.272857  3.512291  13.50  22.54  17.141429  3.099637
2009-03-22  15.071429  5.736757  11.34  22.95  16.282857  4.758899
2009-03-29  15.762857  4.481182  15.34  22.50  18.512857  2.841612
2009-04-05  13.291429  2.489434   7.17  13.17  11.425714  2.294231
2009-04-12  10.220000  2.970713   6.38  15.34  10.810000  3.112213
2009-04-19  10.894286  4.531449   5.66  20.46   9.945714  5.063967
2009-04-26  11.934286  4.363293   4.96  20.08  12.297143  5.145855
2009-05-03  12.102857  4.605843   2.67  12.67   8.345714  4.097706
2009-05-10  15.510000  9.578225   3.83  26.58  15.360000  9.959587
2009-05-17   9.751429  1.737752   3.33  13.70   8.778571  3.545812
2009-05-24   8.921429  1.833498   5.91  14.96  10.834286  2.943778
2009-05-31  11.797143  1.921091   8.00  17.96  13.072857  4.196628
2009-06-07  13.544286  2.347828   8.75  16.38  13.012857  2.665244
2009-06-14   9.344286  5.147760   5.96  19.83  11.090000  4.920505
2009-06-21  15.840000  4.625682  13.75  24.71  17.251429  4.120799
2009-06-28  15.142857  3.270982  11.63  21.50  17.398571  3.353677
2009-07-05  13.951429  6.906066   8.50  21.29  13.563333  5.571060
2009-07-12  11.150000  4.132896   5.96  17.41  12.528571  3.810347
2009-07-19  12.610000  4.571958   9.13  21.96  12.768571  4.369395
2009-07-26  11.054286  6.858933   5.41  25.37  11.290000  7.878411
2009-08-02   8.907143  1.699811   9.08  13.75  10.850000  1.977734
2009-08-09  12.902857  3.879582   5.88  20.25  12.695714  5.621378
2009-08-16  11.441429  3.337691   8.38  16.08  12.805000  2.809824
2009-08-23  15.945714  4.180641  12.62  24.30  17.274286  4.301127
2009-08-30  18.632857  6.587146   8.29  22.54  16.398571  5.345688
2009-09-06  10.102857  5.245562   3.37  20.25   9.450000  5.984809
2009-09-13  14.177143  6.559222   5.79  16.71  12.238571  4.416131
2009-09-20  14.397143  7.827805   5.25  33.09  15.900000  9.007547
2009-09-27  15.501429  4.150134   7.12  16.21  12.790000  3.430384
2009-10-04  11.244286  6.948402   4.04  19.62  11.141429  6.348379
2009-10-11  13.160000  5.946198   8.33  21.04  14.600000  4.685310
2009-10-18  17.392857  5.428166  10.75  33.45  20.605714  9.698781
2009-10-25  17.220000  5.892198  13.46  30.88  22.255714  5.768986
2009-11-01  13.945714  4.547647   9.83  20.62  14.772857  4.094475
2009-11-08  12.922857  4.381597   9.71  23.58  16.494286  5.371371
2009-11-15   7.381429  2.594863   2.75  15.54   8.417143  4.989782
2009-11-22   6.262857  3.368599   2.00  10.34   6.905714  2.749599
2009-11-29  14.945714  5.514248   4.25  22.58  15.428571  7.394832
2009-12-06  12.637143  5.677408  11.17  29.33  16.951429  6.060799
2009-12-13  16.868571  4.211039   7.58  19.41  14.872857  4.690841
2009-12-20   9.374286  5.867552   3.92  21.12   9.338571  6.315181
2009-12-27  11.727143  4.866274   2.62  16.62  10.464286  4.631464

[52 rows x 48 columns]